<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dummy2">

    <xacro:property name="base_width" value="0.43"/>
    <xacro:property name="base_length" value="0.60"/>
    <xacro:property name="base_height" value="0.10"/>

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.06"/>

    <xacro:property name="wheel_ygap" value="0.02"/>

    <xacro:property name="wheel_xoff" value="0.305"/>
    <xacro:property name="wheel_zoff" value="0.02"/>
    <xacro:property name="shock_travel" value = "0.09"/>

    <xacro:macro name="box_inertia" params="m w h d">
            <inertia ixx="${(m/12)*(h*h + d*d)}" ixy="0.0" ixz="0.0"
                     iyy="${(m/12)*(w*w + d*d)}" iyz="0.0"
                     izz="${(m/12)*(w*w + h*h)}"/>
    </xacro:macro>

    <xacro:macro name="wheel_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz="0.0"
                     izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * m * (r*r)}" iyz="0.0"
                    izz="${(2/5) * m * (r*r)}"/>
        </inertial>
  </xacro:macro>

    <link name="base_footprint"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>


    <link name="body_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
          <mass value="2.6"/>
          <xacro:box_inertia m="2.6" w="${base_width}" d="${base_length}" h="${base_height}"/>
        </inertial>
    </link>


    <joint name="body_joint" type="fixed">
        <origin xyz="0.0 0.0 ${2*base_height}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="body_link"/>
    </joint>

     <link name="back_left_wheel_link">
      <xacro:wheel_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>

    <link name="back_right_wheel_link">
      <xacro:wheel_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>

    <link name="back_left_wheel_shock">
        <visual>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
        <material name="silver">
          <color rgba="0.75 0.75 0.75 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
                ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <link name="back_right_wheel_shock">
        <visual>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
        <material name="silver">
          <color rgba="0.75 0.75 0.75 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
                ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="back_left_shock_joint" type="prismatic">
      <origin xyz="${-wheel_xoff} ${(base_width/2)} ${shock_travel}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="back_left_wheel_shock"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    </joint>

    <joint name="back_left_wheel_joint" type="continuous">
      <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 0.0"/>
      <parent link="back_left_wheel_shock"/>
      <child link="back_left_wheel_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="10000" velocity="500"/>
    </joint>

    <joint name="back_right_shock_joint" type="prismatic">
      <origin xyz="${-wheel_xoff} ${-(base_width/2)} ${shock_travel}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="back_right_wheel_shock"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
    </joint>

    <joint name="back_right_wheel_joint" type="continuous">
      <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 0.0"/>
      <parent link="back_right_wheel_shock"/>
      <child link="back_right_wheel_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="10000" velocity="500"/>
    </joint>

    <link name="front_left_wheel_steer">
      <visual>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
                 ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <link name="front_left_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <link name="front_left_wheel_shock">
      <visual>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
        <material name="silver">
          <color rgba="0.75 0.75 0.75 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
                ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="front_left_shock_joint" type="prismatic">
      <limit lower="0" upper="${shock_travel}" effort="100" velocity="100"/>
      <axis xyz="0 0 1"/>
      <parent link="base_link"/>
      <child link="front_left_wheel_shock"/>
      <origin rpy="0 0 0" xyz="${wheel_xoff} ${(base_width/2)} ${shock_travel}"/>
    </joint>

    <joint name="front_left_wheel_steer_joint" type="revolute">
      <limit lower="-1" upper="1" effort="1" velocity="5"/>
      <axis xyz="0 0 1"/>
      <parent link="front_left_wheel_shock"/>
      <child link="front_left_wheel_steer"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <joint name="front_left_wheel_joint" type="continuous">
      <axis xyz="0 0 1"/>
      <parent link="front_left_wheel_steer"/>
      <child link="front_left_wheel"/>
      <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
    </joint>

    <link name="front_right_wheel_steer">
      <visual>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
                ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <link name="front_right_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <link name="front_right_wheel_shock">
      <visual>
      <origin xyz="0 0 0.1" rpt="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.05"/>
      </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.015" iyy="0.0375" izz="0.0375"
                ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="front_right_shock_joint" type="prismatic">
      <limit lower="0.0" upper="${shock_travel}" effort="100" velocity="100"/>
      <axis xyz="0.0 0.0 1.0"/>
      <parent link="base_link"/>
      <child link="front_right_wheel_shock"/>
      <origin rpy="0 0 0" xyz="${wheel_xoff} ${-(base_width/2)} ${shock_travel}"/>
    </joint>

    <joint name="front_right_wheel_steer_joint" type="revolute">
      <limit lower="-1" upper="1" effort="1" velocity="5"/>
      <axis xyz="0.0 0.0 1.0"/>
      <parent link="front_right_wheel_shock"/>
      <child link="front_right_wheel_steer"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="front_right_wheel_joint" type="continuous">
      <axis xyz="0 0.0 1.0"/>
      <parent link="front_right_wheel_steer"/>
      <child link="front_right_wheel"/>
      <origin rpy="${-pi/2} 0.0 0.0" xyz="0 0 0"/>
    </joint>

  <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1e-5"/>
      <inertia ixx="1e-6"  ixy="0"  ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <cylinder radius="0.108" length="0.22"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <cylinder radius="0.108" length="0.12"/>
      </geometry>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.215 0.0 0.30" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>3</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>419</samples>
            <resolution>0.86</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>15.0</max>
          <resolution>0.86</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- <gazebo>
    <plugin name="ackermann_gazebo_plugin" filename="libackermann_gazebo_plugin.so">
    </plugin>
  </gazebo> -->
</robot>
